### ISSUE TITLE
Inconsistent variable naming for integration in documentation/examples

### ISSUE THREAD

**Issue by talavis** [ds-wizard/ds-wizard#184]
It would be great if you can standardise the variable naming for `integration.yml`.

At https://docs.ds-wizard.org/en/latest/admin/configuration.html#config-server-integration you use:
```
dbase:
  apiKey: topSecretDBaseApiKey
  baseUrl: https://api.dbase.example:10666
  someConfig: someValue4Integration
```

In the config example (`engine-wizard/config/integration-test.yml.example`) you use:
```
ontologyPortal:
  baseurl: https://mockserver.ds-wizard.org
  apikey: '123456'
```

And `dsw:lifesciences:2.0.0` from the registry seems to expect:
```
fairsharing:
  apiUrl: <url>
  apiKey: <key>
```
